require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GuiToolsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GuiTool. As you add validations to GuiTool, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GuiToolsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET exercise_content" do
    it "assigns the requested exercise as @exercise"
      exercise_content = Exercise.create! valid attributes
      get :edit, {3 => exercise_content.to_param}, valid_session
      assigns(:exercise_content).should eq(exercise_content)
    end
  end 

  describe "GET index" do
    it "assigns all gui_tools as @gui_tools" do
      gui_tool = GuiTool.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gui_tools)).to eq([gui_tool])
    end
  end

  describe "GET show" do
    it "assigns the requested gui_tool as @gui_tool" do
      gui_tool = GuiTool.create! valid_attributes
      get :show, {:id => gui_tool.to_param}, valid_session
      expect(assigns(:gui_tool)).to eq(gui_tool)
    end
  end

  describe "GET new" do
    it "assigns a new gui_tool as @gui_tool" do
      get :new, {}, valid_session
      expect(assigns(:gui_tool)).to be_a_new(GuiTool)
    end
  end

  describe "GET edit" do
    it "assigns the requested gui_tool as @gui_tool" do
      gui_tool = GuiTool.create! valid_attributes
      get :edit, {:id => gui_tool.to_param}, valid_session
      expect(assigns(:gui_tool)).to eq(gui_tool)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GuiTool" do
        expect {
          post :create, {:gui_tool => valid_attributes}, valid_session
        }.to change(GuiTool, :count).by(1)
      end

      it "assigns a newly created gui_tool as @gui_tool" do
        post :create, {:gui_tool => valid_attributes}, valid_session
        expect(assigns(:gui_tool)).to be_a(GuiTool)
        expect(assigns(:gui_tool)).to be_persisted
      end

      it "redirects to the created gui_tool" do
        post :create, {:gui_tool => valid_attributes}, valid_session
        expect(response).to redirect_to(GuiTool.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gui_tool as @gui_tool" do
        post :create, {:gui_tool => invalid_attributes}, valid_session
        expect(assigns(:gui_tool)).to be_a_new(GuiTool)
      end

      it "re-renders the 'new' template" do
        post :create, {:gui_tool => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gui_tool" do
        gui_tool = GuiTool.create! valid_attributes
        put :update, {:id => gui_tool.to_param, :gui_tool => new_attributes}, valid_session
        gui_tool.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested gui_tool as @gui_tool" do
        gui_tool = GuiTool.create! valid_attributes
        put :update, {:id => gui_tool.to_param, :gui_tool => valid_attributes}, valid_session
        expect(assigns(:gui_tool)).to eq(gui_tool)
      end

      it "redirects to the gui_tool" do
        gui_tool = GuiTool.create! valid_attributes
        put :update, {:id => gui_tool.to_param, :gui_tool => valid_attributes}, valid_session
        expect(response).to redirect_to(gui_tool)
      end
    end

    describe "with invalid params" do
      it "assigns the gui_tool as @gui_tool" do
        gui_tool = GuiTool.create! valid_attributes
        put :update, {:id => gui_tool.to_param, :gui_tool => invalid_attributes}, valid_session
        expect(assigns(:gui_tool)).to eq(gui_tool)
      end

      it "re-renders the 'edit' template" do
        gui_tool = GuiTool.create! valid_attributes
        put :update, {:id => gui_tool.to_param, :gui_tool => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gui_tool" do
      gui_tool = GuiTool.create! valid_attributes
      expect {
        delete :destroy, {:id => gui_tool.to_param}, valid_session
      }.to change(GuiTool, :count).by(-1)
    end

    it "redirects to the gui_tools list" do
      gui_tool = GuiTool.create! valid_attributes
      delete :destroy, {:id => gui_tool.to_param}, valid_session
      expect(response).to redirect_to(gui_tools_url)
    end
  end

end
